/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SentryTestRouteImport } from './routes/sentry-test'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as StrategyTokenRouteImport } from './routes/strategy.$token'
import { Route as ReviewTokenRouteImport } from './routes/review.$token'
import { Route as OnboardTokenRouteImport } from './routes/onboard.$token'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppReviewRouteImport } from './routes/app/review'
import { Route as AppHubsRouteImport } from './routes/app/hubs'
import { Route as AppExportsRouteImport } from './routes/app/exports'
import { Route as AppEngagementRouteImport } from './routes/app/engagement'
import { Route as AppCreativeConflictsRouteImport } from './routes/app/creative-conflicts'
import { Route as AppContentLibraryRouteImport } from './routes/app/content-library'
import { Route as AppClientsRouteImport } from './routes/app/clients'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AppBrandDnaRouteImport } from './routes/app/brand-dna'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppClientsIndexRouteImport } from './routes/app/clients.index'
import { Route as AppHubsNewRouteImport } from './routes/app/hubs.new'
import { Route as AppHubsHubIdRouteImport } from './routes/app/hubs.$hubId'
import { Route as AppClientsClientIdRouteImport } from './routes/app/clients.$clientId'
import { Route as AppClientsClientIdIndexRouteImport } from './routes/app/clients.$clientId.index'
import { Route as AppClientsClientIdSettingsRouteImport } from './routes/app/clients.$clientId.settings'
import { Route as AppClientsClientIdBrandDnaRouteImport } from './routes/app/clients.$clientId.brand-dna'
import { Route as AppClientsClientIdAdmiredProfilesRouteImport } from './routes/app/clients.$clientId.admired-profiles'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SentryTestRoute = SentryTestRouteImport.update({
  id: '/sentry-test',
  path: '/sentry-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const StrategyTokenRoute = StrategyTokenRouteImport.update({
  id: '/strategy/$token',
  path: '/strategy/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewTokenRoute = ReviewTokenRouteImport.update({
  id: '/review/$token',
  path: '/review/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardTokenRoute = OnboardTokenRouteImport.update({
  id: '/onboard/$token',
  path: '/onboard/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppHubsRoute = AppHubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => AppRoute,
} as any)
const AppExportsRoute = AppExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AppRoute,
} as any)
const AppEngagementRoute = AppEngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => AppRoute,
} as any)
const AppCreativeConflictsRoute = AppCreativeConflictsRouteImport.update({
  id: '/creative-conflicts',
  path: '/creative-conflicts',
  getParentRoute: () => AppRoute,
} as any)
const AppContentLibraryRoute = AppContentLibraryRouteImport.update({
  id: '/content-library',
  path: '/content-library',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandDnaRoute = AppBrandDnaRouteImport.update({
  id: '/brand-dna',
  path: '/brand-dna',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppHubsNewRoute = AppHubsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppHubsRoute,
} as any)
const AppHubsHubIdRoute = AppHubsHubIdRouteImport.update({
  id: '/$hubId',
  path: '/$hubId',
  getParentRoute: () => AppHubsRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppClientsClientIdIndexRoute = AppClientsClientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientsClientIdRoute,
} as any)
const AppClientsClientIdSettingsRoute =
  AppClientsClientIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppClientsClientIdRoute,
  } as any)
const AppClientsClientIdBrandDnaRoute =
  AppClientsClientIdBrandDnaRouteImport.update({
    id: '/brand-dna',
    path: '/brand-dna',
    getParentRoute: () => AppClientsClientIdRoute,
  } as any)
const AppClientsClientIdAdmiredProfilesRoute =
  AppClientsClientIdAdmiredProfilesRouteImport.update({
    id: '/admired-profiles',
    path: '/admired-profiles',
    getParentRoute: () => AppClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sentry-test': typeof SentryTestRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/brand-dna': typeof AppBrandDnaRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/content-library': typeof AppContentLibraryRoute
  '/app/creative-conflicts': typeof AppCreativeConflictsRoute
  '/app/engagement': typeof AppEngagementRoute
  '/app/exports': typeof AppExportsRoute
  '/app/hubs': typeof AppHubsRouteWithChildren
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/onboard/$token': typeof OnboardTokenRoute
  '/review/$token': typeof ReviewTokenRoute
  '/strategy/$token': typeof StrategyTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRouteWithChildren
  '/app/hubs/$hubId': typeof AppHubsHubIdRoute
  '/app/hubs/new': typeof AppHubsNewRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/clients/$clientId/admired-profiles': typeof AppClientsClientIdAdmiredProfilesRoute
  '/app/clients/$clientId/brand-dna': typeof AppClientsClientIdBrandDnaRoute
  '/app/clients/$clientId/settings': typeof AppClientsClientIdSettingsRoute
  '/app/clients/$clientId/': typeof AppClientsClientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sentry-test': typeof SentryTestRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/brand-dna': typeof AppBrandDnaRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/content-library': typeof AppContentLibraryRoute
  '/app/creative-conflicts': typeof AppCreativeConflictsRoute
  '/app/engagement': typeof AppEngagementRoute
  '/app/exports': typeof AppExportsRoute
  '/app/hubs': typeof AppHubsRouteWithChildren
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/onboard/$token': typeof OnboardTokenRoute
  '/review/$token': typeof ReviewTokenRoute
  '/strategy/$token': typeof StrategyTokenRoute
  '/app': typeof AppIndexRoute
  '/app/hubs/$hubId': typeof AppHubsHubIdRoute
  '/app/hubs/new': typeof AppHubsNewRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/clients/$clientId/admired-profiles': typeof AppClientsClientIdAdmiredProfilesRoute
  '/app/clients/$clientId/brand-dna': typeof AppClientsClientIdBrandDnaRoute
  '/app/clients/$clientId/settings': typeof AppClientsClientIdSettingsRoute
  '/app/clients/$clientId': typeof AppClientsClientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sentry-test': typeof SentryTestRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/brand-dna': typeof AppBrandDnaRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/content-library': typeof AppContentLibraryRoute
  '/app/creative-conflicts': typeof AppCreativeConflictsRoute
  '/app/engagement': typeof AppEngagementRoute
  '/app/exports': typeof AppExportsRoute
  '/app/hubs': typeof AppHubsRouteWithChildren
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/onboard/$token': typeof OnboardTokenRoute
  '/review/$token': typeof ReviewTokenRoute
  '/strategy/$token': typeof StrategyTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRouteWithChildren
  '/app/hubs/$hubId': typeof AppHubsHubIdRoute
  '/app/hubs/new': typeof AppHubsNewRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/clients/$clientId/admired-profiles': typeof AppClientsClientIdAdmiredProfilesRoute
  '/app/clients/$clientId/brand-dna': typeof AppClientsClientIdBrandDnaRoute
  '/app/clients/$clientId/settings': typeof AppClientsClientIdSettingsRoute
  '/app/clients/$clientId/': typeof AppClientsClientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sentry-test'
    | '/signup'
    | '/app/analytics'
    | '/app/brand-dna'
    | '/app/calendar'
    | '/app/clients'
    | '/app/content-library'
    | '/app/creative-conflicts'
    | '/app/engagement'
    | '/app/exports'
    | '/app/hubs'
    | '/app/review'
    | '/app/settings'
    | '/onboard/$token'
    | '/review/$token'
    | '/strategy/$token'
    | '/app/'
    | '/app/clients/$clientId'
    | '/app/hubs/$hubId'
    | '/app/hubs/new'
    | '/app/clients/'
    | '/app/clients/$clientId/admired-profiles'
    | '/app/clients/$clientId/brand-dna'
    | '/app/clients/$clientId/settings'
    | '/app/clients/$clientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sentry-test'
    | '/signup'
    | '/app/analytics'
    | '/app/brand-dna'
    | '/app/calendar'
    | '/app/content-library'
    | '/app/creative-conflicts'
    | '/app/engagement'
    | '/app/exports'
    | '/app/hubs'
    | '/app/review'
    | '/app/settings'
    | '/onboard/$token'
    | '/review/$token'
    | '/strategy/$token'
    | '/app'
    | '/app/hubs/$hubId'
    | '/app/hubs/new'
    | '/app/clients'
    | '/app/clients/$clientId/admired-profiles'
    | '/app/clients/$clientId/brand-dna'
    | '/app/clients/$clientId/settings'
    | '/app/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sentry-test'
    | '/signup'
    | '/app/analytics'
    | '/app/brand-dna'
    | '/app/calendar'
    | '/app/clients'
    | '/app/content-library'
    | '/app/creative-conflicts'
    | '/app/engagement'
    | '/app/exports'
    | '/app/hubs'
    | '/app/review'
    | '/app/settings'
    | '/onboard/$token'
    | '/review/$token'
    | '/strategy/$token'
    | '/app/'
    | '/app/clients/$clientId'
    | '/app/hubs/$hubId'
    | '/app/hubs/new'
    | '/app/clients/'
    | '/app/clients/$clientId/admired-profiles'
    | '/app/clients/$clientId/brand-dna'
    | '/app/clients/$clientId/settings'
    | '/app/clients/$clientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SentryTestRoute: typeof SentryTestRoute
  SignupRoute: typeof SignupRoute
  OnboardTokenRoute: typeof OnboardTokenRoute
  ReviewTokenRoute: typeof ReviewTokenRoute
  StrategyTokenRoute: typeof StrategyTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentry-test': {
      id: '/sentry-test'
      path: '/sentry-test'
      fullPath: '/sentry-test'
      preLoaderRoute: typeof SentryTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/strategy/$token': {
      id: '/strategy/$token'
      path: '/strategy/$token'
      fullPath: '/strategy/$token'
      preLoaderRoute: typeof StrategyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$token': {
      id: '/review/$token'
      path: '/review/$token'
      fullPath: '/review/$token'
      preLoaderRoute: typeof ReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/$token': {
      id: '/onboard/$token'
      path: '/onboard/$token'
      fullPath: '/onboard/$token'
      preLoaderRoute: typeof OnboardTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hubs': {
      id: '/app/hubs'
      path: '/hubs'
      fullPath: '/app/hubs'
      preLoaderRoute: typeof AppHubsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exports': {
      id: '/app/exports'
      path: '/exports'
      fullPath: '/app/exports'
      preLoaderRoute: typeof AppExportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/engagement': {
      id: '/app/engagement'
      path: '/engagement'
      fullPath: '/app/engagement'
      preLoaderRoute: typeof AppEngagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/creative-conflicts': {
      id: '/app/creative-conflicts'
      path: '/creative-conflicts'
      fullPath: '/app/creative-conflicts'
      preLoaderRoute: typeof AppCreativeConflictsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content-library': {
      id: '/app/content-library'
      path: '/content-library'
      fullPath: '/app/content-library'
      preLoaderRoute: typeof AppContentLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/brand-dna': {
      id: '/app/brand-dna'
      path: '/brand-dna'
      fullPath: '/app/brand-dna'
      preLoaderRoute: typeof AppBrandDnaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/': {
      id: '/app/clients/'
      path: '/'
      fullPath: '/app/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/app/hubs/new': {
      id: '/app/hubs/new'
      path: '/new'
      fullPath: '/app/hubs/new'
      preLoaderRoute: typeof AppHubsNewRouteImport
      parentRoute: typeof AppHubsRoute
    }
    '/app/hubs/$hubId': {
      id: '/app/hubs/$hubId'
      path: '/$hubId'
      fullPath: '/app/hubs/$hubId'
      preLoaderRoute: typeof AppHubsHubIdRouteImport
      parentRoute: typeof AppHubsRoute
    }
    '/app/clients/$clientId': {
      id: '/app/clients/$clientId'
      path: '/$clientId'
      fullPath: '/app/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/app/clients/$clientId/': {
      id: '/app/clients/$clientId/'
      path: '/'
      fullPath: '/app/clients/$clientId/'
      preLoaderRoute: typeof AppClientsClientIdIndexRouteImport
      parentRoute: typeof AppClientsClientIdRoute
    }
    '/app/clients/$clientId/settings': {
      id: '/app/clients/$clientId/settings'
      path: '/settings'
      fullPath: '/app/clients/$clientId/settings'
      preLoaderRoute: typeof AppClientsClientIdSettingsRouteImport
      parentRoute: typeof AppClientsClientIdRoute
    }
    '/app/clients/$clientId/brand-dna': {
      id: '/app/clients/$clientId/brand-dna'
      path: '/brand-dna'
      fullPath: '/app/clients/$clientId/brand-dna'
      preLoaderRoute: typeof AppClientsClientIdBrandDnaRouteImport
      parentRoute: typeof AppClientsClientIdRoute
    }
    '/app/clients/$clientId/admired-profiles': {
      id: '/app/clients/$clientId/admired-profiles'
      path: '/admired-profiles'
      fullPath: '/app/clients/$clientId/admired-profiles'
      preLoaderRoute: typeof AppClientsClientIdAdmiredProfilesRouteImport
      parentRoute: typeof AppClientsClientIdRoute
    }
  }
}

interface AppClientsClientIdRouteChildren {
  AppClientsClientIdAdmiredProfilesRoute: typeof AppClientsClientIdAdmiredProfilesRoute
  AppClientsClientIdBrandDnaRoute: typeof AppClientsClientIdBrandDnaRoute
  AppClientsClientIdSettingsRoute: typeof AppClientsClientIdSettingsRoute
  AppClientsClientIdIndexRoute: typeof AppClientsClientIdIndexRoute
}

const AppClientsClientIdRouteChildren: AppClientsClientIdRouteChildren = {
  AppClientsClientIdAdmiredProfilesRoute:
    AppClientsClientIdAdmiredProfilesRoute,
  AppClientsClientIdBrandDnaRoute: AppClientsClientIdBrandDnaRoute,
  AppClientsClientIdSettingsRoute: AppClientsClientIdSettingsRoute,
  AppClientsClientIdIndexRoute: AppClientsClientIdIndexRoute,
}

const AppClientsClientIdRouteWithChildren =
  AppClientsClientIdRoute._addFileChildren(AppClientsClientIdRouteChildren)

interface AppClientsRouteChildren {
  AppClientsClientIdRoute: typeof AppClientsClientIdRouteWithChildren
  AppClientsIndexRoute: typeof AppClientsIndexRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsClientIdRoute: AppClientsClientIdRouteWithChildren,
  AppClientsIndexRoute: AppClientsIndexRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppHubsRouteChildren {
  AppHubsHubIdRoute: typeof AppHubsHubIdRoute
  AppHubsNewRoute: typeof AppHubsNewRoute
}

const AppHubsRouteChildren: AppHubsRouteChildren = {
  AppHubsHubIdRoute: AppHubsHubIdRoute,
  AppHubsNewRoute: AppHubsNewRoute,
}

const AppHubsRouteWithChildren =
  AppHubsRoute._addFileChildren(AppHubsRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBrandDnaRoute: typeof AppBrandDnaRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppContentLibraryRoute: typeof AppContentLibraryRoute
  AppCreativeConflictsRoute: typeof AppCreativeConflictsRoute
  AppEngagementRoute: typeof AppEngagementRoute
  AppExportsRoute: typeof AppExportsRoute
  AppHubsRoute: typeof AppHubsRouteWithChildren
  AppReviewRoute: typeof AppReviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBrandDnaRoute: AppBrandDnaRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppContentLibraryRoute: AppContentLibraryRoute,
  AppCreativeConflictsRoute: AppCreativeConflictsRoute,
  AppEngagementRoute: AppEngagementRoute,
  AppExportsRoute: AppExportsRoute,
  AppHubsRoute: AppHubsRouteWithChildren,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SentryTestRoute: SentryTestRoute,
  SignupRoute: SignupRoute,
  OnboardTokenRoute: OnboardTokenRoute,
  ReviewTokenRoute: ReviewTokenRoute,
  StrategyTokenRoute: StrategyTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
