/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppReviewRouteImport } from './routes/app/review'
import { Route as AppHubsRouteImport } from './routes/app/hubs'
import { Route as AppClientsRouteImport } from './routes/app/clients'
import { Route as AppBrandDnaRouteImport } from './routes/app/brand-dna'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppHubsNewRouteImport } from './routes/app/hubs.new'
import { Route as AppHubsHubIdRouteImport } from './routes/app/hubs.$hubId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppHubsRoute = AppHubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandDnaRoute = AppBrandDnaRouteImport.update({
  id: '/brand-dna',
  path: '/brand-dna',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppHubsNewRoute = AppHubsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppHubsRoute,
} as any)
const AppHubsHubIdRoute = AppHubsHubIdRouteImport.update({
  id: '/$hubId',
  path: '/$hubId',
  getParentRoute: () => AppHubsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/brand-dna': typeof AppBrandDnaRoute
  '/app/clients': typeof AppClientsRoute
  '/app/hubs': typeof AppHubsRouteWithChildren
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/hubs/$hubId': typeof AppHubsHubIdRoute
  '/app/hubs/new': typeof AppHubsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/brand-dna': typeof AppBrandDnaRoute
  '/app/clients': typeof AppClientsRoute
  '/app/hubs': typeof AppHubsRouteWithChildren
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/hubs/$hubId': typeof AppHubsHubIdRoute
  '/app/hubs/new': typeof AppHubsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/brand-dna': typeof AppBrandDnaRoute
  '/app/clients': typeof AppClientsRoute
  '/app/hubs': typeof AppHubsRouteWithChildren
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/hubs/$hubId': typeof AppHubsHubIdRoute
  '/app/hubs/new': typeof AppHubsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/analytics'
    | '/app/brand-dna'
    | '/app/clients'
    | '/app/hubs'
    | '/app/review'
    | '/app/settings'
    | '/app/'
    | '/app/hubs/$hubId'
    | '/app/hubs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/analytics'
    | '/app/brand-dna'
    | '/app/clients'
    | '/app/hubs'
    | '/app/review'
    | '/app/settings'
    | '/app'
    | '/app/hubs/$hubId'
    | '/app/hubs/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/analytics'
    | '/app/brand-dna'
    | '/app/clients'
    | '/app/hubs'
    | '/app/review'
    | '/app/settings'
    | '/app/'
    | '/app/hubs/$hubId'
    | '/app/hubs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hubs': {
      id: '/app/hubs'
      path: '/hubs'
      fullPath: '/app/hubs'
      preLoaderRoute: typeof AppHubsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/brand-dna': {
      id: '/app/brand-dna'
      path: '/brand-dna'
      fullPath: '/app/brand-dna'
      preLoaderRoute: typeof AppBrandDnaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hubs/new': {
      id: '/app/hubs/new'
      path: '/new'
      fullPath: '/app/hubs/new'
      preLoaderRoute: typeof AppHubsNewRouteImport
      parentRoute: typeof AppHubsRoute
    }
    '/app/hubs/$hubId': {
      id: '/app/hubs/$hubId'
      path: '/$hubId'
      fullPath: '/app/hubs/$hubId'
      preLoaderRoute: typeof AppHubsHubIdRouteImport
      parentRoute: typeof AppHubsRoute
    }
  }
}

interface AppHubsRouteChildren {
  AppHubsHubIdRoute: typeof AppHubsHubIdRoute
  AppHubsNewRoute: typeof AppHubsNewRoute
}

const AppHubsRouteChildren: AppHubsRouteChildren = {
  AppHubsHubIdRoute: AppHubsHubIdRoute,
  AppHubsNewRoute: AppHubsNewRoute,
}

const AppHubsRouteWithChildren =
  AppHubsRoute._addFileChildren(AppHubsRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBrandDnaRoute: typeof AppBrandDnaRoute
  AppClientsRoute: typeof AppClientsRoute
  AppHubsRoute: typeof AppHubsRouteWithChildren
  AppReviewRoute: typeof AppReviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBrandDnaRoute: AppBrandDnaRoute,
  AppClientsRoute: AppClientsRoute,
  AppHubsRoute: AppHubsRouteWithChildren,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
