/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAuthedRouteImport } from './routes/app/_authed'
import { Route as AppAuthedIndexRouteImport } from './routes/app/_authed/index'
import { Route as AppAuthedUpgradeRouteImport } from './routes/app/_authed/upgrade'
import { Route as AppAuthedProjectsNewRouteImport } from './routes/app/_authed/projects/new'
import { Route as AppAuthedProjectsProjectIdRouteImport } from './routes/app/_authed/projects/$projectId'

const AppRouteImport = createFileRoute('/app')()

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedRoute = AppAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthedIndexRoute = AppAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedUpgradeRoute = AppAuthedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedProjectsNewRoute = AppAuthedProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedProjectsProjectIdRoute =
  AppAuthedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppAuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAuthedRouteWithChildren
  '/app/upgrade': typeof AppAuthedUpgradeRoute
  '/app/': typeof AppAuthedIndexRoute
  '/app/projects/$projectId': typeof AppAuthedProjectsProjectIdRoute
  '/app/projects/new': typeof AppAuthedProjectsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppAuthedIndexRoute
  '/app/upgrade': typeof AppAuthedUpgradeRoute
  '/app/projects/$projectId': typeof AppAuthedProjectsProjectIdRoute
  '/app/projects/new': typeof AppAuthedProjectsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/_authed': typeof AppAuthedRouteWithChildren
  '/app/_authed/upgrade': typeof AppAuthedUpgradeRoute
  '/app/_authed/': typeof AppAuthedIndexRoute
  '/app/_authed/projects/$projectId': typeof AppAuthedProjectsProjectIdRoute
  '/app/_authed/projects/new': typeof AppAuthedProjectsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/upgrade'
    | '/app/'
    | '/app/projects/$projectId'
    | '/app/projects/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/upgrade'
    | '/app/projects/$projectId'
    | '/app/projects/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/_authed'
    | '/app/_authed/upgrade'
    | '/app/_authed/'
    | '/app/_authed/projects/$projectId'
    | '/app/_authed/projects/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authed': {
      id: '/app/_authed'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_authed/': {
      id: '/app/_authed/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthedIndexRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/upgrade': {
      id: '/app/_authed/upgrade'
      path: '/upgrade'
      fullPath: '/app/upgrade'
      preLoaderRoute: typeof AppAuthedUpgradeRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/projects/new': {
      id: '/app/_authed/projects/new'
      path: '/projects/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AppAuthedProjectsNewRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/projects/$projectId': {
      id: '/app/_authed/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppAuthedProjectsProjectIdRouteImport
      parentRoute: typeof AppAuthedRoute
    }
  }
}

interface AppAuthedRouteChildren {
  AppAuthedUpgradeRoute: typeof AppAuthedUpgradeRoute
  AppAuthedIndexRoute: typeof AppAuthedIndexRoute
  AppAuthedProjectsProjectIdRoute: typeof AppAuthedProjectsProjectIdRoute
  AppAuthedProjectsNewRoute: typeof AppAuthedProjectsNewRoute
}

const AppAuthedRouteChildren: AppAuthedRouteChildren = {
  AppAuthedUpgradeRoute: AppAuthedUpgradeRoute,
  AppAuthedIndexRoute: AppAuthedIndexRoute,
  AppAuthedProjectsProjectIdRoute: AppAuthedProjectsProjectIdRoute,
  AppAuthedProjectsNewRoute: AppAuthedProjectsNewRoute,
}

const AppAuthedRouteWithChildren = AppAuthedRoute._addFileChildren(
  AppAuthedRouteChildren,
)

interface AppRouteChildren {
  AppAuthedRoute: typeof AppAuthedRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthedRoute: AppAuthedRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
