/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAuthedRouteImport } from './routes/app/_authed'
import { Route as AppAuthedIndexRouteImport } from './routes/app/_authed/index'
import { Route as AppAuthedUpgradeRouteImport } from './routes/app/_authed/upgrade'
import { Route as AppAuthedSprintRouteImport } from './routes/app/_authed/sprint'
import { Route as AppAuthedSettingsRouteImport } from './routes/app/_authed/settings'
import { Route as AppAuthedReviewRouteImport } from './routes/app/_authed/review'
import { Route as AppAuthedCreativeConflictsRouteImport } from './routes/app/_authed/creative-conflicts'
import { Route as AppAuthedAgentRouteImport } from './routes/app/_authed/agent'
import { Route as AppAuthedProjectsIndexRouteImport } from './routes/app/_authed/projects/index'
import { Route as AppAuthedProjectsNewRouteImport } from './routes/app/_authed/projects.new'
import { Route as AppAuthedProjectsProjectIdRouteImport } from './routes/app/_authed/projects.$projectId'
import { Route as AppAuthedHubsHubIdRouteImport } from './routes/app/_authed/hubs.$hubId'
import { Route as AppAuthedProjectsProjectIdSprintRouteImport } from './routes/app/_authed/projects.$projectId.sprint'
import { Route as AppAuthedProjectsProjectIdResearchRouteImport } from './routes/app/_authed/projects.$projectId.research'
import { Route as AppAuthedProjectsProjectIdOfferRouteImport } from './routes/app/_authed/projects.$projectId.offer'
import { Route as AppAuthedProjectsProjectIdCompetitorsRouteImport } from './routes/app/_authed/projects.$projectId.competitors'

const AppRouteImport = createFileRoute('/app')()

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedRoute = AppAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthedIndexRoute = AppAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedUpgradeRoute = AppAuthedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedSprintRoute = AppAuthedSprintRouteImport.update({
  id: '/sprint',
  path: '/sprint',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedSettingsRoute = AppAuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedReviewRoute = AppAuthedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedCreativeConflictsRoute =
  AppAuthedCreativeConflictsRouteImport.update({
    id: '/creative-conflicts',
    path: '/creative-conflicts',
    getParentRoute: () => AppAuthedRoute,
  } as any)
const AppAuthedAgentRoute = AppAuthedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedProjectsIndexRoute = AppAuthedProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedProjectsNewRoute = AppAuthedProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedProjectsProjectIdRoute =
  AppAuthedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppAuthedRoute,
  } as any)
const AppAuthedHubsHubIdRoute = AppAuthedHubsHubIdRouteImport.update({
  id: '/hubs/$hubId',
  path: '/hubs/$hubId',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedProjectsProjectIdSprintRoute =
  AppAuthedProjectsProjectIdSprintRouteImport.update({
    id: '/sprint',
    path: '/sprint',
    getParentRoute: () => AppAuthedProjectsProjectIdRoute,
  } as any)
const AppAuthedProjectsProjectIdResearchRoute =
  AppAuthedProjectsProjectIdResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => AppAuthedProjectsProjectIdRoute,
  } as any)
const AppAuthedProjectsProjectIdOfferRoute =
  AppAuthedProjectsProjectIdOfferRouteImport.update({
    id: '/offer',
    path: '/offer',
    getParentRoute: () => AppAuthedProjectsProjectIdRoute,
  } as any)
const AppAuthedProjectsProjectIdCompetitorsRoute =
  AppAuthedProjectsProjectIdCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AppAuthedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAuthedRouteWithChildren
  '/app/agent': typeof AppAuthedAgentRoute
  '/app/creative-conflicts': typeof AppAuthedCreativeConflictsRoute
  '/app/review': typeof AppAuthedReviewRoute
  '/app/settings': typeof AppAuthedSettingsRoute
  '/app/sprint': typeof AppAuthedSprintRoute
  '/app/upgrade': typeof AppAuthedUpgradeRoute
  '/app/': typeof AppAuthedIndexRoute
  '/app/hubs/$hubId': typeof AppAuthedHubsHubIdRoute
  '/app/projects/$projectId': typeof AppAuthedProjectsProjectIdRouteWithChildren
  '/app/projects/new': typeof AppAuthedProjectsNewRoute
  '/app/projects': typeof AppAuthedProjectsIndexRoute
  '/app/projects/$projectId/competitors': typeof AppAuthedProjectsProjectIdCompetitorsRoute
  '/app/projects/$projectId/offer': typeof AppAuthedProjectsProjectIdOfferRoute
  '/app/projects/$projectId/research': typeof AppAuthedProjectsProjectIdResearchRoute
  '/app/projects/$projectId/sprint': typeof AppAuthedProjectsProjectIdSprintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppAuthedIndexRoute
  '/app/agent': typeof AppAuthedAgentRoute
  '/app/creative-conflicts': typeof AppAuthedCreativeConflictsRoute
  '/app/review': typeof AppAuthedReviewRoute
  '/app/settings': typeof AppAuthedSettingsRoute
  '/app/sprint': typeof AppAuthedSprintRoute
  '/app/upgrade': typeof AppAuthedUpgradeRoute
  '/app/hubs/$hubId': typeof AppAuthedHubsHubIdRoute
  '/app/projects/$projectId': typeof AppAuthedProjectsProjectIdRouteWithChildren
  '/app/projects/new': typeof AppAuthedProjectsNewRoute
  '/app/projects': typeof AppAuthedProjectsIndexRoute
  '/app/projects/$projectId/competitors': typeof AppAuthedProjectsProjectIdCompetitorsRoute
  '/app/projects/$projectId/offer': typeof AppAuthedProjectsProjectIdOfferRoute
  '/app/projects/$projectId/research': typeof AppAuthedProjectsProjectIdResearchRoute
  '/app/projects/$projectId/sprint': typeof AppAuthedProjectsProjectIdSprintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/_authed': typeof AppAuthedRouteWithChildren
  '/app/_authed/agent': typeof AppAuthedAgentRoute
  '/app/_authed/creative-conflicts': typeof AppAuthedCreativeConflictsRoute
  '/app/_authed/review': typeof AppAuthedReviewRoute
  '/app/_authed/settings': typeof AppAuthedSettingsRoute
  '/app/_authed/sprint': typeof AppAuthedSprintRoute
  '/app/_authed/upgrade': typeof AppAuthedUpgradeRoute
  '/app/_authed/': typeof AppAuthedIndexRoute
  '/app/_authed/hubs/$hubId': typeof AppAuthedHubsHubIdRoute
  '/app/_authed/projects/$projectId': typeof AppAuthedProjectsProjectIdRouteWithChildren
  '/app/_authed/projects/new': typeof AppAuthedProjectsNewRoute
  '/app/_authed/projects/': typeof AppAuthedProjectsIndexRoute
  '/app/_authed/projects/$projectId/competitors': typeof AppAuthedProjectsProjectIdCompetitorsRoute
  '/app/_authed/projects/$projectId/offer': typeof AppAuthedProjectsProjectIdOfferRoute
  '/app/_authed/projects/$projectId/research': typeof AppAuthedProjectsProjectIdResearchRoute
  '/app/_authed/projects/$projectId/sprint': typeof AppAuthedProjectsProjectIdSprintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/agent'
    | '/app/creative-conflicts'
    | '/app/review'
    | '/app/settings'
    | '/app/sprint'
    | '/app/upgrade'
    | '/app/'
    | '/app/hubs/$hubId'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/app/projects'
    | '/app/projects/$projectId/competitors'
    | '/app/projects/$projectId/offer'
    | '/app/projects/$projectId/research'
    | '/app/projects/$projectId/sprint'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/agent'
    | '/app/creative-conflicts'
    | '/app/review'
    | '/app/settings'
    | '/app/sprint'
    | '/app/upgrade'
    | '/app/hubs/$hubId'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/app/projects'
    | '/app/projects/$projectId/competitors'
    | '/app/projects/$projectId/offer'
    | '/app/projects/$projectId/research'
    | '/app/projects/$projectId/sprint'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/_authed'
    | '/app/_authed/agent'
    | '/app/_authed/creative-conflicts'
    | '/app/_authed/review'
    | '/app/_authed/settings'
    | '/app/_authed/sprint'
    | '/app/_authed/upgrade'
    | '/app/_authed/'
    | '/app/_authed/hubs/$hubId'
    | '/app/_authed/projects/$projectId'
    | '/app/_authed/projects/new'
    | '/app/_authed/projects/'
    | '/app/_authed/projects/$projectId/competitors'
    | '/app/_authed/projects/$projectId/offer'
    | '/app/_authed/projects/$projectId/research'
    | '/app/_authed/projects/$projectId/sprint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authed': {
      id: '/app/_authed'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_authed/': {
      id: '/app/_authed/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthedIndexRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/upgrade': {
      id: '/app/_authed/upgrade'
      path: '/upgrade'
      fullPath: '/app/upgrade'
      preLoaderRoute: typeof AppAuthedUpgradeRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/sprint': {
      id: '/app/_authed/sprint'
      path: '/sprint'
      fullPath: '/app/sprint'
      preLoaderRoute: typeof AppAuthedSprintRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/settings': {
      id: '/app/_authed/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppAuthedSettingsRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/review': {
      id: '/app/_authed/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppAuthedReviewRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/creative-conflicts': {
      id: '/app/_authed/creative-conflicts'
      path: '/creative-conflicts'
      fullPath: '/app/creative-conflicts'
      preLoaderRoute: typeof AppAuthedCreativeConflictsRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/agent': {
      id: '/app/_authed/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAuthedAgentRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/projects/': {
      id: '/app/_authed/projects/'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppAuthedProjectsIndexRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/projects/new': {
      id: '/app/_authed/projects/new'
      path: '/projects/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AppAuthedProjectsNewRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/projects/$projectId': {
      id: '/app/_authed/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppAuthedProjectsProjectIdRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/hubs/$hubId': {
      id: '/app/_authed/hubs/$hubId'
      path: '/hubs/$hubId'
      fullPath: '/app/hubs/$hubId'
      preLoaderRoute: typeof AppAuthedHubsHubIdRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/projects/$projectId/sprint': {
      id: '/app/_authed/projects/$projectId/sprint'
      path: '/sprint'
      fullPath: '/app/projects/$projectId/sprint'
      preLoaderRoute: typeof AppAuthedProjectsProjectIdSprintRouteImport
      parentRoute: typeof AppAuthedProjectsProjectIdRoute
    }
    '/app/_authed/projects/$projectId/research': {
      id: '/app/_authed/projects/$projectId/research'
      path: '/research'
      fullPath: '/app/projects/$projectId/research'
      preLoaderRoute: typeof AppAuthedProjectsProjectIdResearchRouteImport
      parentRoute: typeof AppAuthedProjectsProjectIdRoute
    }
    '/app/_authed/projects/$projectId/offer': {
      id: '/app/_authed/projects/$projectId/offer'
      path: '/offer'
      fullPath: '/app/projects/$projectId/offer'
      preLoaderRoute: typeof AppAuthedProjectsProjectIdOfferRouteImport
      parentRoute: typeof AppAuthedProjectsProjectIdRoute
    }
    '/app/_authed/projects/$projectId/competitors': {
      id: '/app/_authed/projects/$projectId/competitors'
      path: '/competitors'
      fullPath: '/app/projects/$projectId/competitors'
      preLoaderRoute: typeof AppAuthedProjectsProjectIdCompetitorsRouteImport
      parentRoute: typeof AppAuthedProjectsProjectIdRoute
    }
  }
}

interface AppAuthedProjectsProjectIdRouteChildren {
  AppAuthedProjectsProjectIdCompetitorsRoute: typeof AppAuthedProjectsProjectIdCompetitorsRoute
  AppAuthedProjectsProjectIdOfferRoute: typeof AppAuthedProjectsProjectIdOfferRoute
  AppAuthedProjectsProjectIdResearchRoute: typeof AppAuthedProjectsProjectIdResearchRoute
  AppAuthedProjectsProjectIdSprintRoute: typeof AppAuthedProjectsProjectIdSprintRoute
}

const AppAuthedProjectsProjectIdRouteChildren: AppAuthedProjectsProjectIdRouteChildren =
  {
    AppAuthedProjectsProjectIdCompetitorsRoute:
      AppAuthedProjectsProjectIdCompetitorsRoute,
    AppAuthedProjectsProjectIdOfferRoute: AppAuthedProjectsProjectIdOfferRoute,
    AppAuthedProjectsProjectIdResearchRoute:
      AppAuthedProjectsProjectIdResearchRoute,
    AppAuthedProjectsProjectIdSprintRoute:
      AppAuthedProjectsProjectIdSprintRoute,
  }

const AppAuthedProjectsProjectIdRouteWithChildren =
  AppAuthedProjectsProjectIdRoute._addFileChildren(
    AppAuthedProjectsProjectIdRouteChildren,
  )

interface AppAuthedRouteChildren {
  AppAuthedAgentRoute: typeof AppAuthedAgentRoute
  AppAuthedCreativeConflictsRoute: typeof AppAuthedCreativeConflictsRoute
  AppAuthedReviewRoute: typeof AppAuthedReviewRoute
  AppAuthedSettingsRoute: typeof AppAuthedSettingsRoute
  AppAuthedSprintRoute: typeof AppAuthedSprintRoute
  AppAuthedUpgradeRoute: typeof AppAuthedUpgradeRoute
  AppAuthedIndexRoute: typeof AppAuthedIndexRoute
  AppAuthedHubsHubIdRoute: typeof AppAuthedHubsHubIdRoute
  AppAuthedProjectsProjectIdRoute: typeof AppAuthedProjectsProjectIdRouteWithChildren
  AppAuthedProjectsNewRoute: typeof AppAuthedProjectsNewRoute
  AppAuthedProjectsIndexRoute: typeof AppAuthedProjectsIndexRoute
}

const AppAuthedRouteChildren: AppAuthedRouteChildren = {
  AppAuthedAgentRoute: AppAuthedAgentRoute,
  AppAuthedCreativeConflictsRoute: AppAuthedCreativeConflictsRoute,
  AppAuthedReviewRoute: AppAuthedReviewRoute,
  AppAuthedSettingsRoute: AppAuthedSettingsRoute,
  AppAuthedSprintRoute: AppAuthedSprintRoute,
  AppAuthedUpgradeRoute: AppAuthedUpgradeRoute,
  AppAuthedIndexRoute: AppAuthedIndexRoute,
  AppAuthedHubsHubIdRoute: AppAuthedHubsHubIdRoute,
  AppAuthedProjectsProjectIdRoute: AppAuthedProjectsProjectIdRouteWithChildren,
  AppAuthedProjectsNewRoute: AppAuthedProjectsNewRoute,
  AppAuthedProjectsIndexRoute: AppAuthedProjectsIndexRoute,
}

const AppAuthedRouteWithChildren = AppAuthedRoute._addFileChildren(
  AppAuthedRouteChildren,
)

interface AppRouteChildren {
  AppAuthedRoute: typeof AppAuthedRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthedRoute: AppAuthedRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
